Repository ifplant/ifplant_app, pull requests merged in 2021-11, with the labels that each got.

#20 Feature/11
  assets/images/sample_plant.png
  lib/app/root.dart
  lib/app/route/app_pages.dart
  lib/app/route/app_routes.dart
  lib/app/ui/android/home/home.dart
  lib/app/ui/android/select/components/select_plant_widget.dart
  lib/app/ui/android/select/select_plant.dart
  lib/app/ui/android/select_detail/select_plant_detail.dart
  lib/app/ui/pages/plant_screen.dart
  pubspec.yaml
Labels: widget, ui

#29 Feature/12
  assets/icon/arrow_back.svg
  assets/icon/arrow_less.svg
  assets/icon/level.svg
  assets/icon/light.svg
  assets/icon/temp.svg
  assets/icon/water.svg
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  lib/app/route/app_pages.dart
  lib/app/route/app_routes.dart
  lib/app/ui/android/home/components/selected_plant_list.dart
  lib/app/ui/android/select/components/grid_plant_item.dart
  lib/app/ui/android/select/components/select_plant_widget.dart
  lib/app/ui/android/select/select_plant.dart
  lib/app/ui/android/select_detail/select_plant_detail.dart
  lib/main.dart
  pubspec.yaml
Labels: widget, ui, screen

#32 Feature/13
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  lib/app/binding/init_binding.dart
  lib/app/controller/captured_page/captured_page_controller.dart
  lib/app/controller/controllers.dart
  lib/app/controller/init_controller.dart
  lib/app/root.dart
  lib/app/route/app_pages.dart
  lib/app/route/app_routes.dart
  lib/app/ui/android/appBar/captured_page_appbar.dart
  lib/app/ui/android/appBar/home_appbar.dart
  lib/app/ui/android/captured_page/captured_page.dart
  lib/app/ui/android/captured_page/components/captureble_image.dart
  lib/app/ui/android/home/home.dart
  lib/app/ui/theme/app_color.dart
  lib/app/ui/theme/app_text_theme.dart
  pubspec.yaml
Labels: screen, integration

#33 위젯단위로 코드 분리
  lib/app/ui/android/appBar/select_plant_appbar.dart
  lib/app/ui/android/appBar/select_plant_detail.dart
  lib/app/ui/android/select/select_plant.dart
  lib/app/ui/android/select_detail/components/build_bottom_sheet.dart
  lib/app/ui/android/select_detail/components/plant_svg.dart
  lib/app/ui/android/select_detail/components/show_bottom_appbar.dart
  lib/app/ui/android/select_detail/select_plant_detail.dart
Labels: widget, ui, refactoring

#34 Feature/27
  android/app/src/main/res/drawable/launch_background.xml
  lib/app/controller/home/home_controller.dart
  lib/app/controller/init_controller.dart
  lib/app/route/app_pages.dart
  lib/app/route/app_routes.dart
  lib/app/ui/android/screens.dart
  lib/app/ui/android/select_detail/components/show_bottom_appbar.dart
  lib/app/ui/android/splash_screen/splash_screen.dart
  lib/app/ui/theme/app_text_theme.dart
  lib/main.dart
  pubspec.yaml
Labels: bug, ui, function

#37 Feature/36
  lib/app/route/app_pages.dart
  lib/app/ui/android/appBar/select_plant_appbar.dart
  lib/app/ui/android/home/components/selected_plant_list.dart
  lib/app/ui/android/select_detail/components/show_bottom_appbar.dart
  lib/app/ui/android/select_detail/select_plant_detail.dart
  lib/app/ui/android/splash_screen/splash_screen.dart
  pubspec.yaml
Labels: bug, ui, function
